name: Build and Deploy
on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install and Build
        run: |
          npm ci
          npm run-script build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: build
          repository-name: JakobVogelsang/openscdtest.github.io
          token: ${{ secrets.DEPLOY_KEY }}
